version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_nginx: {}

services:
  django:
    build:
      context: .
      dockerfile: ./docker/production/django/Dockerfile
    image: product_manager_api_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./docker/production/postgres/Dockerfile
    image: product_manager_api_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  nginx:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    image: product_manager_api_production_nginx
    depends_on:
      - django
    volumes:
      - production_nginx:/root/.nginx
    env_file:
      - ./.envs/.production/.nginx
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  redis:
    image: redis:3.2
